@startuml
'https://plantuml.com/class-diagram

Class "Liste de Courses" as listCourse {
-nom: String
-isArchive: bool
-produits: list[Produits]
-quantitéProduits: list[int]

+ajouterProduit(produit)
+supprimerProduit(produit)
+augmenterQuantite(produit, quantite)
+reduireQuantite(produit, quantite)
}

note bottom of listCourse: "quantitéProduits[i] = quantité de Produits[i]"

Class Produit {
-nom: String
-type: TypeProduits
}

Class Menus {
+generateCourses(): listCourse
}
Class Recette {
-nom: String
-type: TypeProduits
}

enum typeProduits {
Végétarien
Végan
Poisson
épicés
Halal
casher
Made in France
Bio
}

Recette -> Produit
listCourse -> Produit
@enduml